# Default values for my-java-app.

# The name of the Java application.
appName: flight-booking-system

# The Docker image to use for the Java application.
image:
  repository: emirsway/galaxytravel:v1.3
  tag: latest
  pullPolicy: IfNotPresent

# The number of replicas to run for the Java application.
replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 85
# The type of Kubernetes service to use for the Java application.

service:
  name: flight-booking-system
  type: LoadBalancer
  port: 8008 # or the desired port number

serviceAccount:
  create: true

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

#helm create galaxy-travel-booking-system
#helm package . 
#helm install flight-booking-system ./galaxy-travel-booking-system-0.3.tgz
#helm uninstall chartname
